### ISSUE TITLE
guidelines on opaque tokens

### ISSUE THREAD

**Issue by ghost** [belgif/rest-security#9]
Security experts from SocSec (Small) favor opaque tokens over self-container ones as they have too many privacy-sensitive scopes.
The REST Security Guide, however, states that authorization server must be configured so that it returns access tokens that are self-contained in lieu of opaque.
@pvdbosch will organize a meeting to discuss this topic.

**Comment by pvdbosch** [comment]
The argument specified in the pull request:
> Indeed, opaque tokens MUST be validated at the authorization server’s token introspection endpoint for each request, which is grossly inefficient.

is related to the other rules that forbids reuse of access tokens, so we'll need to discuss that first (see #10 ). If reuse of access tokens is allowed, the introspect response can be cached as well by the resource server.

The efficiency argument against introspection can only be applied to Category 1-2:
> For RESTful services processing Category 3-4 data, it’s RECOMMENDED to validate all access tokens at the authorization server’s token introspection endpoint (despite the performance penalty).

_edit:_ split the discussion of reusing access tokens to separate issue
